In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

from probly.representation.sampling import sample

s1 = sample.ArraySample(np.arange(12).reshape((3, 4)), 1)
s2 = sample.ArraySample(np.arange(21).reshape((7, 3)), 0)
s1

ArraySample(array=array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), sample_dim=1)

In [3]:
s1.sample_size, s2.sample_size

(4, 7)

In [4]:
s1[0]

array([0, 1, 2, 3])

In [5]:
s2

ArraySample(array=array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]]), sample_dim=0)

In [6]:
s1.concat(s2)

ArraySample(array=array([[ 0,  1,  2,  3,  0,  3,  6,  9, 12, 15, 18],
       [ 4,  5,  6,  7,  1,  4,  7, 10, 13, 16, 19],
       [ 8,  9, 10, 11,  2,  5,  8, 11, 14, 17, 20]]), sample_dim=1)

In [7]:
s1.concat(s2)

ArraySample(array=array([[ 0,  1,  2,  3,  0,  3,  6,  9, 12, 15, 18],
       [ 4,  5,  6,  7,  1,  4,  7, 10, 13, 16, 19],
       [ 8,  9, 10, 11,  2,  5,  8, 11, 14, 17, 20]]), sample_dim=1)

In [8]:
s2.concat(s1)

ArraySample(array=array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]]), sample_dim=0)

In [9]:
s1 * 2

ArraySample(array=array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]]), sample_dim=1)

In [10]:
s1[None, :, :]

ArraySample(array=array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]]), sample_dim=2)

In [11]:
s1

ArraySample(array=array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), sample_dim=1)

In [12]:
np.add.reduce(s1, 0)

ArraySample(array=array([12, 15, 18, 21]), sample_dim=0)

In [13]:
s2

ArraySample(array=array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]]), sample_dim=0)

In [46]:
s2 += 3
s2

ArraySample(array=array([[48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68]]), sample_dim=0)

In [15]:
s1.sample_size

4

In [51]:
s1[0]

array([0, 1, 2, 3])

In [16]:
np.transpose(s1)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [17]:
s1

ArraySample(array=array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), sample_dim=1)

In [18]:
import numpy.testing.overrides as npo

{x.__name__ for x in npo.get_overridable_numpy_array_functions()} - {
    x.__name__ for x in npo.get_overridable_numpy_ufuncs()
}

{'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'append_fields',
 'apply_along_axis',
 'apply_along_fields',
 'apply_over_axes',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array2string',
 'array_equal',
 'array_equiv',
 'array_repr',
 'array_split',
 'array_str',
 'assign_fields_by_name',
 'astype',
 'atleast_1d',
 'atleast_2d',
 'atleast_3d',
 'average',
 'bincount',
 'block',
 'broadcast_arrays',
 'broadcast_to',
 'busday_count',
 'busday_offset',
 'can_cast',
 'cholesky',
 'choose',
 'column_stack',
 'common_type',
 'compress',
 'concatenate',
 'cond',
 'convolve',
 'copy',
 'copyto',
 'corrcoef',
 'correlate',
 'count_nonzero',
 'cov',
 'cross',
 'cumprod',
 'cumsum',
 'cumulative_prod',
 'cumulative_sum',
 'datetime_as_string',
 'delete',
 'det',
 'diag',
 'diag_indices_from',
 'diagflat',
 'diagonal',
 'diff',
 'digitize',
 'dot',
 'drop_fields',
 'dsplit',
 'dstack',
 'ediff1d',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'ei

In [19]:
npo.get_overridable_numpy_ufuncs()

{<ufunc '_center'>,
 <ufunc '_expandtabs'>,
 <ufunc '_expandtabs_length'>,
 <ufunc '_ljust'>,
 <ufunc '_lstrip_chars'>,
 <ufunc '_lstrip_whitespace'>,
 <ufunc '_ones_like'>,
 <ufunc '_partition'>,
 <ufunc '_partition_index'>,
 <ufunc '_replace'>,
 <ufunc '_rjust'>,
 <ufunc '_rpartition'>,
 <ufunc '_rpartition_index'>,
 <ufunc '_rstrip_chars'>,
 <ufunc '_rstrip_whitespace'>,
 <ufunc '_strip_chars'>,
 <ufunc '_strip_whitespace'>,
 <ufunc '_zfill'>,
 <ufunc 'absolute'>,
 <ufunc 'add'>,
 <ufunc 'arccos'>,
 <ufunc 'arccosh'>,
 <ufunc 'arcsin'>,
 <ufunc 'arcsinh'>,
 <ufunc 'arctan'>,
 <ufunc 'arctan2'>,
 <ufunc 'arctanh'>,
 <ufunc 'bitwise_and'>,
 <ufunc 'bitwise_count'>,
 <ufunc 'bitwise_or'>,
 <ufunc 'bitwise_xor'>,
 <ufunc 'cbrt'>,
 <ufunc 'ceil'>,
 <ufunc 'clip'>,
 <ufunc 'conjugate'>,
 <ufunc 'copysign'>,
 <ufunc 'cos'>,
 <ufunc 'cosh'>,
 <ufunc 'count'>,
 <ufunc 'deg2rad'>,
 <ufunc 'degrees'>,
 <ufunc 'divide'>,
 <ufunc 'divmod'>,
 <ufunc 'endswith'>,
 <ufunc 'equal'>,
 <ufunc 'exp'>,


In [20]:
s3 = s1.copy()

In [21]:
np.argmax(s1, axis=1)

array([3, 3, 3])

In [22]:
np.apply_along_axis(np.sum, 0, s1)

array([12, 15, 18, 21])

In [23]:
np.cumsum(s1, axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [24]:
np.add.accumulate(s1, axis=0)

ArraySample(array=array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]]), sample_dim=0)

In [25]:
s1

ArraySample(array=array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), sample_dim=1)

In [26]:
funcs = [
    "all",
    "allclose",
    "amax",
    "amin",
    "angle",
    "any",
    "append",
    "append_fields",
    "apply_along_axis",
    "apply_along_fields",
    "apply_over_axes",
    "argmax",
    "argmin",
    "argpartition",
    "argsort",
    "argwhere",
    "around",
    "array2string",
    "array_equal",
    "array_equiv",
    "array_repr",
    "array_split",
    "array_str",
    "assign_fields_by_name",
    "astype",
    "atleast_1d",
    "atleast_2d",
    "atleast_3d",
    "average",
    "bincount",
    "block",
    "broadcast_arrays",
    "broadcast_to",
    "busday_count",
    "busday_offset",
    "can_cast",
    "cholesky",
    "choose",
    "column_stack",
    "common_type",
    "compress",
    "concatenate",
    "cond",
    "convolve",
    "copy",
    "copyto",
    "corrcoef",
    "correlate",
    "count_nonzero",
    "cov",
    "cross",
    "cumprod",
    "cumsum",
    "cumulative_prod",
    "cumulative_sum",
    "datetime_as_string",
    "delete",
    "det",
    "diag",
    "diag_indices_from",
    "diagflat",
    "diagonal",
    "diff",
    "digitize",
    "dot",
    "drop_fields",
    "dsplit",
    "dstack",
    "ediff1d",
    "eig",
    "eigh",
    "eigvals",
    "eigvalsh",
    "einsum",
    "einsum_path",
    "empty_like",
    "expand_dims",
    "extract",
    "eye",
    "fill_diagonal",
    "find_duplicates",
    "fix",
    "flatnonzero",
    "flip",
    "fliplr",
    "flipud",
    "fromfunction",
    "full",
    "full_like",
    "genfromtxt",
    "geomspace",
    "gradient",
    "histogram",
    "histogram2d",
    "histogram_bin_edges",
    "histogramdd",
    "hsplit",
    "hstack",
    "i0",
    "identity",
    "imag",
    "in1d",
    "inner",
    "insert",
    "interp",
    "intersect1d",
    "inv",
    "is_busday",
    "isclose",
    "iscomplex",
    "iscomplexobj",
    "isin",
    "isneginf",
    "isposinf",
    "isreal",
    "isrealobj",
    "ix_",
    "join_by",
    "kron",
    "lexsort",
    "linspace",
    "loadtxt",
    "logn",
    "logspace",
    "lstsq",
    "matrix_norm",
    "matrix_power",
    "matrix_rank",
    "matrix_transpose",
    "max",
    "may_share_memory",
    "mean",
    "median",
    "merge_arrays",
    "meshgrid",
    "min",
    "min_scalar_type",
    "moveaxis",
    "multi_dot",
    "nan_to_num",
    "nanargmax",
    "nanargmin",
    "nancumprod",
    "nancumsum",
    "nanmax",
    "nanmean",
    "nanmedian",
    "nanmin",
    "nanpercentile",
    "nanprod",
    "nanquantile",
    "nanstd",
    "nansum",
    "nanvar",
    "ndim",
    "nonzero",
    "norm",
    "ones",
    "ones_like",
    "outer",
    "packbits",
    "pad",
    "partition",
    "percentile",
    "piecewise",
    "pinv",
    "place",
    "poly",
    "polyadd",
    "polyder",
    "polydiv",
    "polyfit",
    "polyint",
    "polymul",
    "polysub",
    "polyval",
    "prod",
    "ptp",
    "put",
    "put_along_axis",
    "putmask",
    "qr",
    "quantile",
    "ravel",
    "ravel_multi_index",
    "real",
    "real_if_close",
    "rec_append_fields",
    "rec_drop_fields",
    "rec_join",
    "recursive_fill_fields",
    "rename_fields",
    "repack_fields",
    "repeat",
    "require",
    "require_fields",
    "reshape",
    "resize",
    "result_type",
    "roll",
    "rollaxis",
    "roots",
    "rot90",
    "round",
    "save",
    "savetxt",
    "savez",
    "savez_compressed",
    "searchsorted",
    "select",
    "setdiff1d",
    "setxor1d",
    "shape",
    "shares_memory",
    "sinc",
    "size",
    "sliding_window_view",
    "slogdet",
    "solve",
    "sort",
    "sort_complex",
    "split",
    "squeeze",
    "stack",
    "stack_arrays",
    "std",
    "structured_to_unstructured",
    "sum",
    "svd",
    "svdvals",
    "swapaxes",
    "take",
    "take_along_axis",
    "tensordot",
    "tensorinv",
    "tensorsolve",
    "tile",
    "trace",
    "transpose",
    "trapezoid",
    "tri",
    "tril",
    "tril_indices_from",
    "trim_zeros",
    "triu",
    "triu_indices_from",
    "union1d",
    "unique",
    "unique_all",
    "unique_counts",
    "unique_inverse",
    "unique_values",
    "unpackbits",
    "unravel_index",
    "unstack",
    "unstructured_to_structured",
    "unwrap",
    "vander",
    "var",
    "vdot",
    "vector_norm",
    "vsplit",
    "vstack",
    "where",
    "zeros_like",
]

In [27]:
s1

ArraySample(array=array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), sample_dim=1)

In [28]:
for n in funcs:
    f = getattr(np, n, None)
    if f is None:
        continue
    try:
        r = f(s1, axis=0)
        if isinstance(r, (sample.Sample, np.number, float, int)):
            continue
        print(n, f, r)
    except Exception:
        pass
        # print(n, "failed:", e)

argmax <function argmax at 0x7f5c65664220> [2 2 2 2]
argmin <function argmin at 0x7f5c65664360> [0 0 0 0]
argsort <function argsort at 0x7f5c656640e0> [[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]
average <function average at 0x7f5c643087c0> [4. 5. 6. 7.]
concatenate <built-in function concatenate> [ 0  1  2  3  4  5  6  7  8  9 10 11]
count_nonzero <function count_nonzero at 0x7f5c65667c40> [2 3 3 3]
cumprod <function cumprod at 0x7f5c65665f80> [[  0   1   2   3]
 [  0   5  12  21]
 [  0  45 120 231]]
cumsum <function cumsum at 0x7f5c65665800> [[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]
cumulative_prod <function cumulative_prod at 0x7f5c65665580> [[  0   1   2   3]
 [  0   5  12  21]
 [  0  45 120 231]]
cumulative_sum <function cumulative_sum at 0x7f5c656656c0> [[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]
diff <function diff at 0x7f5c64308ea0> [[4 4 4 4]
 [4 4 4 4]]
expand_dims <function expand_dims at 0x7f5c64317b00> [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
gradient <function gradien

In [29]:
npo.get_overridable_numpy_array_functions()

{<function bincount at 0x7f5c656226f0>,
 <function busday_count at 0x7f5c65623870>,
 <function busday_offset at 0x7f5c656236b0>,
 <function can_cast at 0x7f5c656189b0>,
 <function concatenate at 0x7f5c6560feb0>,
 <function copyto at 0x7f5c65622bf0>,
 <function datetime_as_string at 0x7f5c65623a30>,
 <function dot at 0x7f5c656225b0>,
 <function empty_like at 0x7f5c6753edb0>,
 <function inner at 0x7f5c6757a430>,
 <function is_busday at 0x7f5c656234f0>,
 <function lexsort at 0x7f5c65618f70>,
 <function may_share_memory at 0x7f5c65623330>,
 <function min_scalar_type at 0x7f5c65618db0>,
 <function packbits at 0x7f5c65622df0>,
 <function putmask at 0x7f5c65622cf0>,
 <function ravel_multi_index at 0x7f5c65622870>,
 <function result_type at 0x7f5c65622470>,
 <function shares_memory at 0x7f5c65623170>,
 <function unpackbits at 0x7f5c65622fb0>,
 <function unravel_index at 0x7f5c65622a30>,
 <function vdot at 0x7f5c65622630>,
 <function where at 0x7f5c65618cf0>,
 <function all at 0x7f5c6566d5f0>,


In [30]:
a = np.arange(8).reshape((2, 2, 2))

a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
a.sum(axis=(0, 2), keepdims=True)

array([[[10],
        [18]]])

In [13]:
import numpy as np
import torch

x = np.arange(12).reshape(2, 3, 2)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [28]:
torch.tensor([1]).__array__()

array([1])

In [68]:
x[:, np.array([[1], [0]]), np.array([[1, 0]])].shape

(2, 2, 2)

In [ ]:
x[:, np.array([[1], [0]]), np.array([[1, 0]])].shape

In [39]:
x[torch.tensor([1]).numpy(), :, torch.tensor([0]).numpy()]

array([[ 6,  8, 10]])

In [92]:
np.int32(3).__index__()

3

In [ ]:
np.arange(16).reshape(2, 2, 2, 2)[:, np.array([0]), :, np.array([0])]

array([[[ 0,  2],
        [ 8, 10]]])

In [119]:
np.arange(8).reshape((2, 2, 2))[np.array([[True, False], [False, True]]), 0]

array([0, 6])

In [104]:
(slice(None), np.array([1, 2]), slice(None)).index(Ellipsis)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [96]:
np.array([False]).dtype == np.bool_

True

In [94]:
np.broadcast_shapes((1,), (10, 20), (1, 20), (10, 1))

(10, 20)

In [72]:
np.array(1).__index__()

1

In [84]:
x[[[[0], [1]]], [True, False, True], [[[0, 1]]]]

array([[[ 0,  5],
        [ 6, 11]]])

In [73]:
np.array(1).shape

()

In [88]:
np.array(1)

array(1)

In [75]:
np.broadcast_shapes((2, 1), (1, 2), ())

(2, 2)

In [52]:
(3).__index__()

3

In [ ]:
torch.tensor([1, 2]).__index__()

TypeError: only integer tensors of a single element can be converted to an index

In [69]:
(3.5).__index__()

AttributeError: 'float' object has no attribute '__index__'

In [42]:
x[np.array(torch.tensor([1]), dtype=object), :, np.array(torch.tensor([0]), dtype=object)]

/tmp/ipykernel_30538/3273752126.py:1: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  x[np.array(torch.tensor([1]), dtype=object), :, np.array(torch.tensor([0]), dtype=object)]


IndexError: arrays used as indices must be of integer (or boolean) type

In [11]:
isinstance(3, np.integer)

False

In [57]:
torch.tensor([3]).__index__()

3