In [33]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [34]:
def f(): ...


class A:
    def __init__(self, x: int):
        self.x = x

    def __call__(self, *args, **kwds):
        pass

    def method(self):
        return self.x


one = A(1)
two = A(2)

one

In [35]:
import numpy as np

from probly.representation.sampling import sample

s1 = sample.ArraySample(np.arange(12).reshape((3, 4)), 1)
s2 = sample.ArraySample(np.arange(21).reshape((7, 3)), 0)
s1

ArraySample(array=array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), sample_dim=1)

In [36]:
s1.sample_size, s2.sample_size

(4, 7)

In [37]:
s1.samples[0]

array([0, 4, 8])

In [38]:
s2

ArraySample(array=array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]]), sample_dim=0)

In [39]:
s1.samples

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [40]:
s2.samples

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [41]:
s1.concat(s2)

ArraySample(array=array([[ 0,  1,  2,  3,  0,  3,  6,  9, 12, 15, 18],
       [ 4,  5,  6,  7,  1,  4,  7, 10, 13, 16, 19],
       [ 8,  9, 10, 11,  2,  5,  8, 11, 14, 17, 20]]), sample_dim=1)

In [42]:
s1.concat(s2).move_sample_dim(0)

ArraySample(array=array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]]), sample_dim=0)

In [43]:
s2.concat(s1).move_sample_dim(0)

ArraySample(array=array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]]), sample_dim=0)

In [44]:
s1 * 2

ArraySample(array=array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]]), sample_dim=1)

In [45]:
np.add.reduce(s1, 0)

ArraySample(array=array([12, 15, 18, 21]), sample_dim=1)

In [46]:
s2

ArraySample(array=array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]]), sample_dim=0)

In [47]:
s2 += 3
s2

ArraySample(array=array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]]), sample_dim=0)

In [48]:
s1.sample_size

4

In [49]:
np.transpose(s1)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [50]:
s1

ArraySample(array=array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), sample_dim=1)

In [51]:
import numpy.testing.overrides as npo

{x.__name__ for x in npo.get_overridable_numpy_array_functions()} - {
    x.__name__ for x in npo.get_overridable_numpy_ufuncs()
}

{'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'append_fields',
 'apply_along_axis',
 'apply_along_fields',
 'apply_over_axes',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array2string',
 'array_equal',
 'array_equiv',
 'array_repr',
 'array_split',
 'array_str',
 'assign_fields_by_name',
 'astype',
 'atleast_1d',
 'atleast_2d',
 'atleast_3d',
 'average',
 'bincount',
 'block',
 'broadcast_arrays',
 'broadcast_to',
 'busday_count',
 'busday_offset',
 'can_cast',
 'cholesky',
 'choose',
 'column_stack',
 'common_type',
 'compress',
 'concatenate',
 'cond',
 'convolve',
 'copy',
 'copyto',
 'corrcoef',
 'correlate',
 'count_nonzero',
 'cov',
 'cross',
 'cumprod',
 'cumsum',
 'cumulative_prod',
 'cumulative_sum',
 'datetime_as_string',
 'delete',
 'det',
 'diag',
 'diag_indices_from',
 'diagflat',
 'diagonal',
 'diff',
 'digitize',
 'dot',
 'drop_fields',
 'dsplit',
 'dstack',
 'ediff1d',
 'eig',
 'eigh',
 'eigvals',
 'eigvalsh',
 'ei

In [52]:
npo.get_overridable_numpy_ufuncs()

{<ufunc '_center'>,
 <ufunc '_expandtabs'>,
 <ufunc '_expandtabs_length'>,
 <ufunc '_ljust'>,
 <ufunc '_lstrip_chars'>,
 <ufunc '_lstrip_whitespace'>,
 <ufunc '_ones_like'>,
 <ufunc '_partition'>,
 <ufunc '_partition_index'>,
 <ufunc '_replace'>,
 <ufunc '_rjust'>,
 <ufunc '_rpartition'>,
 <ufunc '_rpartition_index'>,
 <ufunc '_rstrip_chars'>,
 <ufunc '_rstrip_whitespace'>,
 <ufunc '_strip_chars'>,
 <ufunc '_strip_whitespace'>,
 <ufunc '_zfill'>,
 <ufunc 'absolute'>,
 <ufunc 'add'>,
 <ufunc 'arccos'>,
 <ufunc 'arccosh'>,
 <ufunc 'arcsin'>,
 <ufunc 'arcsinh'>,
 <ufunc 'arctan'>,
 <ufunc 'arctan2'>,
 <ufunc 'arctanh'>,
 <ufunc 'bitwise_and'>,
 <ufunc 'bitwise_count'>,
 <ufunc 'bitwise_or'>,
 <ufunc 'bitwise_xor'>,
 <ufunc 'cbrt'>,
 <ufunc 'ceil'>,
 <ufunc 'clip'>,
 <ufunc 'conjugate'>,
 <ufunc 'copysign'>,
 <ufunc 'cos'>,
 <ufunc 'cosh'>,
 <ufunc 'count'>,
 <ufunc 'deg2rad'>,
 <ufunc 'degrees'>,
 <ufunc 'divide'>,
 <ufunc 'divmod'>,
 <ufunc 'endswith'>,
 <ufunc 'equal'>,
 <ufunc 'exp'>,


In [53]:
s3 = s1.copy()

In [54]:
np.argmax(s1, axis=1)

array([3, 3, 3])

In [55]:
np.apply_along_axis(np.sum, 0, s1)

array([12, 15, 18, 21])

In [56]:
np.cumsum(s1, axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [57]:
np.add.accumulate(s1, axis=0)

ArraySample(array=array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]]), sample_dim=1)

In [58]:
s1

ArraySample(array=array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), sample_dim=1)

In [59]:
funcs = [
    "all",
    "allclose",
    "amax",
    "amin",
    "angle",
    "any",
    "append",
    "append_fields",
    "apply_along_axis",
    "apply_along_fields",
    "apply_over_axes",
    "argmax",
    "argmin",
    "argpartition",
    "argsort",
    "argwhere",
    "around",
    "array2string",
    "array_equal",
    "array_equiv",
    "array_repr",
    "array_split",
    "array_str",
    "assign_fields_by_name",
    "astype",
    "atleast_1d",
    "atleast_2d",
    "atleast_3d",
    "average",
    "bincount",
    "block",
    "broadcast_arrays",
    "broadcast_to",
    "busday_count",
    "busday_offset",
    "can_cast",
    "cholesky",
    "choose",
    "column_stack",
    "common_type",
    "compress",
    "concatenate",
    "cond",
    "convolve",
    "copy",
    "copyto",
    "corrcoef",
    "correlate",
    "count_nonzero",
    "cov",
    "cross",
    "cumprod",
    "cumsum",
    "cumulative_prod",
    "cumulative_sum",
    "datetime_as_string",
    "delete",
    "det",
    "diag",
    "diag_indices_from",
    "diagflat",
    "diagonal",
    "diff",
    "digitize",
    "dot",
    "drop_fields",
    "dsplit",
    "dstack",
    "ediff1d",
    "eig",
    "eigh",
    "eigvals",
    "eigvalsh",
    "einsum",
    "einsum_path",
    "empty_like",
    "expand_dims",
    "extract",
    "eye",
    "fill_diagonal",
    "find_duplicates",
    "fix",
    "flatnonzero",
    "flip",
    "fliplr",
    "flipud",
    "fromfunction",
    "full",
    "full_like",
    "genfromtxt",
    "geomspace",
    "gradient",
    "histogram",
    "histogram2d",
    "histogram_bin_edges",
    "histogramdd",
    "hsplit",
    "hstack",
    "i0",
    "identity",
    "imag",
    "in1d",
    "inner",
    "insert",
    "interp",
    "intersect1d",
    "inv",
    "is_busday",
    "isclose",
    "iscomplex",
    "iscomplexobj",
    "isin",
    "isneginf",
    "isposinf",
    "isreal",
    "isrealobj",
    "ix_",
    "join_by",
    "kron",
    "lexsort",
    "linspace",
    "loadtxt",
    "logn",
    "logspace",
    "lstsq",
    "matrix_norm",
    "matrix_power",
    "matrix_rank",
    "matrix_transpose",
    "max",
    "may_share_memory",
    "mean",
    "median",
    "merge_arrays",
    "meshgrid",
    "min",
    "min_scalar_type",
    "moveaxis",
    "multi_dot",
    "nan_to_num",
    "nanargmax",
    "nanargmin",
    "nancumprod",
    "nancumsum",
    "nanmax",
    "nanmean",
    "nanmedian",
    "nanmin",
    "nanpercentile",
    "nanprod",
    "nanquantile",
    "nanstd",
    "nansum",
    "nanvar",
    "ndim",
    "nonzero",
    "norm",
    "ones",
    "ones_like",
    "outer",
    "packbits",
    "pad",
    "partition",
    "percentile",
    "piecewise",
    "pinv",
    "place",
    "poly",
    "polyadd",
    "polyder",
    "polydiv",
    "polyfit",
    "polyint",
    "polymul",
    "polysub",
    "polyval",
    "prod",
    "ptp",
    "put",
    "put_along_axis",
    "putmask",
    "qr",
    "quantile",
    "ravel",
    "ravel_multi_index",
    "real",
    "real_if_close",
    "rec_append_fields",
    "rec_drop_fields",
    "rec_join",
    "recursive_fill_fields",
    "rename_fields",
    "repack_fields",
    "repeat",
    "require",
    "require_fields",
    "reshape",
    "resize",
    "result_type",
    "roll",
    "rollaxis",
    "roots",
    "rot90",
    "round",
    "save",
    "savetxt",
    "savez",
    "savez_compressed",
    "searchsorted",
    "select",
    "setdiff1d",
    "setxor1d",
    "shape",
    "shares_memory",
    "sinc",
    "size",
    "sliding_window_view",
    "slogdet",
    "solve",
    "sort",
    "sort_complex",
    "split",
    "squeeze",
    "stack",
    "stack_arrays",
    "std",
    "structured_to_unstructured",
    "sum",
    "svd",
    "svdvals",
    "swapaxes",
    "take",
    "take_along_axis",
    "tensordot",
    "tensorinv",
    "tensorsolve",
    "tile",
    "trace",
    "transpose",
    "trapezoid",
    "tri",
    "tril",
    "tril_indices_from",
    "trim_zeros",
    "triu",
    "triu_indices_from",
    "union1d",
    "unique",
    "unique_all",
    "unique_counts",
    "unique_inverse",
    "unique_values",
    "unpackbits",
    "unravel_index",
    "unstack",
    "unstructured_to_structured",
    "unwrap",
    "vander",
    "var",
    "vdot",
    "vector_norm",
    "vsplit",
    "vstack",
    "where",
    "zeros_like",
]

In [66]:
s1

ArraySample(array=array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), sample_dim=1)

In [ ]:
for n in funcs:
    f = getattr(np, n, None)
    if f is None:
        continue
    try:
        r = f(s1, axis=0)
        if isinstance(r, (sample.Sample, np.number, float, int)):
            continue
        print(n, f, r)
    except Exception:
        pass
        # print(n, "failed:", e)

argmax <function argmax at 0x7f1f1410b920> [2 2 2 2]
argmin <function argmin at 0x7f1f1410ba60> [0 0 0 0]
argsort <function argsort at 0x7f1f1410b7e0> [[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]
average <function average at 0x7f1f14037420> [4. 5. 6. 7.]
count_nonzero <function count_nonzero at 0x7f1f1413b380> [2 3 3 3]
cumprod <function cumprod at 0x7f1f141396c0> [[  0   1   2   3]
 [  0   5  12  21]
 [  0  45 120 231]]
cumsum <function cumsum at 0x7f1f14138f40> [[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]
cumulative_prod <function cumulative_prod at 0x7f1f14138cc0> [[  0   1   2   3]
 [  0   5  12  21]
 [  0  45 120 231]]
cumulative_sum <function cumulative_sum at 0x7f1f14138e00> [[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]
diff <function diff at 0x7f1f14037b00> [[4 4 4 4]
 [4 4 4 4]]
expand_dims <function expand_dims at 0x7f1f140667a0> [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
flip <function flip at 0x7f1f140371a0> [[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
gradient <function grad

In [67]:
npo.get_overridable_numpy_array_functions()

{<function bincount at 0x7f1f147f3bb0>,
 <function busday_count at 0x7f1f14104c70>,
 <function busday_offset at 0x7f1f14104ab0>,
 <function can_cast at 0x7f1f148e89b0>,
 <function concatenate at 0x7f1f147e6830>,
 <function copyto at 0x7f1f14104070>,
 <function datetime_as_string at 0x7f1f14104db0>,
 <function dot at 0x7f1f147f3a70>,
 <function empty_like at 0x7f1f15c8d2f0>,
 <function inner at 0x7f1f147e53b0>,
 <function is_busday at 0x7f1f141048f0>,
 <function lexsort at 0x7f1f148b65f0>,
 <function may_share_memory at 0x7f1f14104730>,
 <function min_scalar_type at 0x7f1f148e82b0>,
 <function packbits at 0x7f1f14104230>,
 <function putmask at 0x7f1f14104130>,
 <function ravel_multi_index at 0x7f1f147f3cf0>,
 <function result_type at 0x7f1f147f3930>,
 <function shares_memory at 0x7f1f141045b0>,
 <function unpackbits at 0x7f1f141043f0>,
 <function unravel_index at 0x7f1f147f3eb0>,
 <function vdot at 0x7f1f147f3af0>,
 <function where at 0x7f1f147e64f0>,
 <function all at 0x7f1f14135cf0>,
