In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np

from probly.representation.sampling import sample

s1 = sample.ArraySample(np.arange(12).reshape((3, 4)), 1)
s2 = sample.ArraySample(np.arange(21).reshape((7, 3)), 0)
s1, s2

(ArraySample(array=array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), sample_axis=1),
 ArraySample(array=array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17],
        [18, 19, 20]]), sample_axis=0))

In [3]:
s1 * 3

ArraySample(array=array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]]), sample_axis=1)

In [4]:
np.sum(s1, axis=(0, 1), keepdims=True)

ArraySample(array=array([[66]]), sample_axis=1)

In [5]:
np.ravel(s1, order="F").reshape((3, 1, 4, 1), order="F")

array([[[[ 0],
         [ 1],
         [ 2],
         [ 3]]],


       [[[ 4],
         [ 5],
         [ 6],
         [ 7]]],


       [[[ 8],
         [ 9],
         [10],
         [11]]]])

In [6]:
s1

ArraySample(array=array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), sample_axis=1)

In [7]:
s1.sample_size, s2.sample_size

(4, 7)

In [8]:
s2

ArraySample(array=array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]]), sample_axis=0)

In [9]:
s1.concat(s2)

ArraySample(array=array([[ 0,  1,  2,  3,  0,  3,  6,  9, 12, 15, 18],
       [ 4,  5,  6,  7,  1,  4,  7, 10, 13, 16, 19],
       [ 8,  9, 10, 11,  2,  5,  8, 11, 14, 17, 20]]), sample_axis=1)

In [10]:
s2.concat(s1)

ArraySample(array=array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]]), sample_axis=0)

In [11]:
s1 * 2

ArraySample(array=array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]]), sample_axis=1)

In [12]:
s1[None, None, :, :-2, None]

ArraySample(array=array([[[[[0],
          [1]],

         [[4],
          [5]],

         [[8],
          [9]]]]]), sample_axis=3)

In [13]:
np.add.reduce(s1, 0)

ArraySample(array=array([12, 15, 18, 21]), sample_axis=0)

In [14]:
np.add.reduce(s1, -1)

array([ 6, 22, 38])

In [15]:
s2 += 3
s2

ArraySample(array=array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]]), sample_axis=0)

In [16]:
np.transpose(s1)

ArraySample(array=array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]]), sample_axis=0)

In [17]:
np.argmax(s1, axis=1)

array([3, 3, 3])

In [20]:
np.apply_along_axis(np.sum, 0, s1)

ArraySample(array=array([12, 15, 18, 21]), sample_axis=0)

In [ ]:
np.cumsum(s1, axis=1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [ ]:
np.add.accumulate(s1, axis=0)

ArraySample(array=array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]]), sample_axis=0)

In [ ]:
s1

ArraySample(array=array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), sample_axis=1)

In [21]:
funcs = [
    "all",
    "allclose",
    "amax",
    "amin",
    "angle",
    "any",
    "append",
    "append_fields",
    "apply_along_axis",
    "apply_along_fields",
    "apply_over_axes",
    "argmax",
    "argmin",
    "argpartition",
    "argsort",
    "argwhere",
    "around",
    "array2string",
    "array_equal",
    "array_equiv",
    "array_repr",
    "array_split",
    "array_str",
    "assign_fields_by_name",
    "astype",
    "atleast_1d",
    "atleast_2d",
    "atleast_3d",
    "average",
    "bincount",
    "block",
    "broadcast_arrays",
    "broadcast_to",
    "busday_count",
    "busday_offset",
    "can_cast",
    "cholesky",
    "choose",
    "column_stack",
    "common_type",
    "compress",
    "concatenate",
    "cond",
    "convolve",
    "copy",
    "copyto",
    "corrcoef",
    "correlate",
    "count_nonzero",
    "cov",
    "cross",
    "cumprod",
    "cumsum",
    "cumulative_prod",
    "cumulative_sum",
    "datetime_as_string",
    "delete",
    "det",
    "diag",
    "diag_indices_from",
    "diagflat",
    "diagonal",
    "diff",
    "digitize",
    "dot",
    "drop_fields",
    "dsplit",
    "dstack",
    "ediff1d",
    "eig",
    "eigh",
    "eigvals",
    "eigvalsh",
    "einsum",
    "einsum_path",
    "empty_like",
    "expand_dims",
    "extract",
    "eye",
    "fill_diagonal",
    "find_duplicates",
    "fix",
    "flatnonzero",
    "flip",
    "fliplr",
    "flipud",
    "fromfunction",
    "full",
    "full_like",
    "genfromtxt",
    "geomspace",
    "gradient",
    "histogram",
    "histogram2d",
    "histogram_bin_edges",
    "histogramdd",
    "hsplit",
    "hstack",
    "i0",
    "identity",
    "imag",
    "in1d",
    "inner",
    "insert",
    "interp",
    "intersect1d",
    "inv",
    "is_busday",
    "isclose",
    "iscomplex",
    "iscomplexobj",
    "isin",
    "isneginf",
    "isposinf",
    "isreal",
    "isrealobj",
    "ix_",
    "join_by",
    "kron",
    "lexsort",
    "linspace",
    "loadtxt",
    "logn",
    "logspace",
    "lstsq",
    "matrix_norm",
    "matrix_power",
    "matrix_rank",
    "matrix_transpose",
    "max",
    "may_share_memory",
    "mean",
    "median",
    "merge_arrays",
    "meshgrid",
    "min",
    "min_scalar_type",
    "moveaxis",
    "multi_dot",
    "nan_to_num",
    "nanargmax",
    "nanargmin",
    "nancumprod",
    "nancumsum",
    "nanmax",
    "nanmean",
    "nanmedian",
    "nanmin",
    "nanpercentile",
    "nanprod",
    "nanquantile",
    "nanstd",
    "nansum",
    "nanvar",
    "ndim",
    "nonzero",
    "norm",
    "ones",
    "ones_like",
    "outer",
    "packbits",
    "pad",
    "partition",
    "percentile",
    "piecewise",
    "pinv",
    "place",
    "poly",
    "polyadd",
    "polyder",
    "polydiv",
    "polyfit",
    "polyint",
    "polymul",
    "polysub",
    "polyval",
    "prod",
    "ptp",
    "put",
    "put_along_axis",
    "putmask",
    "qr",
    "quantile",
    "ravel",
    "ravel_multi_index",
    "real",
    "real_if_close",
    "rec_append_fields",
    "rec_drop_fields",
    "rec_join",
    "recursive_fill_fields",
    "rename_fields",
    "repack_fields",
    "repeat",
    "require",
    "require_fields",
    "reshape",
    "resize",
    "result_type",
    "roll",
    "rollaxis",
    "roots",
    "rot90",
    "round",
    "save",
    "savetxt",
    "savez",
    "savez_compressed",
    "searchsorted",
    "select",
    "setdiff1d",
    "setxor1d",
    "shape",
    "shares_memory",
    "sinc",
    "size",
    "sliding_window_view",
    "slogdet",
    "solve",
    "sort",
    "sort_complex",
    "split",
    "squeeze",
    "stack",
    "stack_arrays",
    "std",
    "structured_to_unstructured",
    "sum",
    "svd",
    "svdvals",
    "swapaxes",
    "take",
    "take_along_axis",
    "tensordot",
    "tensorinv",
    "tensorsolve",
    "tile",
    "trace",
    "transpose",
    "trapezoid",
    "tri",
    "tril",
    "tril_indices_from",
    "trim_zeros",
    "triu",
    "triu_indices_from",
    "union1d",
    "unique",
    "unique_all",
    "unique_counts",
    "unique_inverse",
    "unique_values",
    "unpackbits",
    "unravel_index",
    "unstack",
    "unstructured_to_structured",
    "unwrap",
    "vander",
    "var",
    "vdot",
    "vector_norm",
    "vsplit",
    "vstack",
    "where",
    "zeros_like",
]

In [24]:
for n in funcs:
    f = getattr(np, n, None)
    if f is None:
        continue
    try:
        r = f(s1, axis=0)
        if isinstance(r, (sample.Sample, np.number, float, int)):
            continue
        print(n, f, r)
    except Exception:  # noqa: BLE001, S110
        pass
        # print(n, "failed:", e)  # noqa: ERA001

argsort <function argsort at 0x7fec40e200e0> [[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]
concatenate <built-in function concatenate> [ 0  1  2  3  4  5  6  7  8  9 10 11]
cumprod <function cumprod at 0x7fec40e21f80> [[  0   1   2   3]
 [  0   5  12  21]
 [  0  45 120 231]]
cumsum <function cumsum at 0x7fec40e21800> [[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]
cumulative_prod <function cumulative_prod at 0x7fec40e21580> [[  0   1   2   3]
 [  0   5  12  21]
 [  0  45 120 231]]
cumulative_sum <function cumulative_sum at 0x7fec40e216c0> [[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]
diff <function diff at 0x7fec40320ea0> [[4 4 4 4]
 [4 4 4 4]]
gradient <function gradient at 0x7fec40320d60> [[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]
lexsort <built-in function lexsort> [0 1 2 3]
nancumprod <function nancumprod at 0x7fec4032a340> [[  0   1   2   3]
 [  0   5  12  21]
 [  0  45 120 231]]
nancumsum <function nancumsum at 0x7fec4032a200> [[ 0  1  2  3]
 [ 4  6  8 10]
 [12 15 18 21]]
nanmean <function 

In [ ]:
a = np.arange(8).reshape((2, 2, 2))

a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
np.zeros((10, 13, 17)).transpose((1, 2))

ValueError: axes don't match array

In [ ]:
np.zeros((5, 5, 5, 10))[None, :, np.array([[1, 2]]), None, np.array([[3], [4]]), :].shape

(2, 2, 1, 5, 1, 10)

In [ ]:
s1

ArraySample(array=array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), sample_axis=1)

In [ ]:
s1.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])